### ISSUE TITLE
fields parameter is undocumented

### ISSUE THREAD

**Issue by ralphvandenhoudt** [everit-org/jira-worklog-query-plugin#15]
We wanted to have the commentBody of the worklog in the json result and looked into the sourcecode how to add it. We found that the functionality is allready available but not in the documentation.

**Comment by balazs-zsoldos** [comment]
Thanks for the feedback. I will ask my colleage to fix this.

**Comment by balazs-zsoldos** [comment]
Wiki updated. Readme points to Wiki
