### ISSUE TITLE
Minor version number in the request.

### ISSUE THREAD

**Issue by StefanPrintezis** [everit-org/jira-worklog-query-plugin#17]
Why is the minor & patch version in the request url?

> /rest/jira-worklog-query/1.2.0/find/worklogsByIssues

If the version is added for incompatible API changes, shouldn't it only contain the Major number?

**Comment by balazs-zsoldos** [comment]
Good question. I think the next version will come out with /1/ in the URL.

As much as I remember, Jira contained the full version before (I am not 100% sure) and we copied the know-how from there. Since that, Jira uses the major version only, too.

**Comment by attila-kiss-it** [comment]
We will fix this issue in the next major release (2.x).

**Comment by StefanPrintezis** [comment]
Thank you.

**Comment by bordatesz** [comment]
Hi StefanPrintezis!

I am pleased to let you know that this issue has been fixed in the new version, which can be found on the [Atlassian Marketplace](https://marketplace.atlassian.com/plugins/org.everit.jira.worklog.query.plugin.core) as well.

**Comment by attila-kiss-it** [comment]
Fixed in https://github.com/everit-org/jira-worklog-query-plugin/releases/tag/v2.0.1
