### ISSUE TITLE
New build for Jira 7.0

### ISSUE THREAD

**Issue by ghost** [everit-org/jira-worklog-query-plugin#22]
Hi.
Please, update plugin for jira 7.0.

**Comment by balazs-zsoldos** [comment]
Hi,

we are working on it. New release will come within a few days.

Regards,
Balazs

**Comment by bordatesz** [comment]
Hi naffix!

I am pleased to inform you that the update is complete.  The new version can be found on the [Atlassian Marketplace](https://marketplace.atlassian.com/plugins/org.everit.jira.worklog.query.plugin.core) as well.

**Comment by attila-kiss-it** [comment]
Fixed in https://github.com/everit-org/jira-worklog-query-plugin/releases/tag/v2.0.1
