### ISSUE TITLE
worklogByIssues  returns wrong number of issues

### ISSUE THREAD

**Issue by stampthecoder** [everit-org/jira-worklog-query-plugin#29]
Whenever you search using jql param  for the worklog by issues rest call,  I get the wrong number of issues back. This needs to be fixed because thats core to why anyone would use it.

**Comment by bordatesz** [comment]
Hi! We'll look into it.

**Comment by bordatesz** [comment]
Which version of the plugin do you use?
Do you have permission to view every issue, that you searching with the JQL?
Did you set the 'maxResults' parameter for a bigger query?
'worklogByIssues' only returns issues that have at least one worklog. Can you check this?

**Comment by stampthecoder** [comment]
First off thank you for a great product. There is NOTHING out there that gives this functionality. I developed something similiar but this is much more robust. 
1. I have my URL set to latest
2. The maxResults  was set to a large number to get all the issues. I ran into the issue running a  query against a timespan that didn't have many issues.
3. I ran an internal filter that returns a larger issue set than what I am receiving. I am using a base jira-user that does not have permissions potentially that can see certain issues. What permissions would I need set to read all issues from each user? This can be an issue.

**Comment by bordatesz** [comment]
@stampthecoder Hi there!
1. The plugin respects and not violate the JIRA permission schemes, so if you as an authenticated  user (or the group you are in) don't have the permission in JIRA to view every issue, then you will not see them in the query response. To test this, please make a query and a search (on the JIRA issue search screen) with the same [authenticated](http://www.everit.org/jira-worklog-query-plugin/#authentication) user, and check the results. In most cases, we use this plugin with a crafted and unique JIRA user with administrator permissions to read all issues from each user, eg. for reporting.
2. As is mentioned, 'worklogByIssues' only returns issues that have at least one worklog. 

To check the proper functioning of the plugin:
1. Authenticate in the browser and/or the application where you want to use the plugin with the same user.
2. Run a similar query like this: /rest/jira-worklog-query/1/find/worklogsByIssues?maxResults=500&group= **_the group to query_** &startDate= **_from_** &endDate= **_to_** &jql=project%20%3D%20 **_the project_**
3. Run the equivalent JQL search in the JIRA Issue search page: project = **_the project_** AND worklogDate>= **_from_** AND worklogDate < **_to_** AND worklogAuthor in membersOf( **_the group to query_** )
4. Check the difference in the number of Issues.

When I did the above-described steps, I got equal numbers.

**Comment by stampthecoder** [comment]
Thank you, I will utilize this query to test. Appreciate your work.

**Comment by bordatesz** [comment]
@stampthecoder : Hi! Did you check the querys I suggested? Is this problem still persist?

**Comment by stampthecoder** [comment]
I believe the issue is because the patch for the enhancement didn't get
applied to   legacy release for JIRA releases less than 7. I upgraded to 7
but having some issues with a 400 bad request error now. However it is not
related to the accuracy issue. You applied the fix to the new jira 7
release so I should be good. I'll let you know
