### ISSUE TITLE
wrong Json response for intervals

### ISSUE THREAD

**Issue by a-aristar** [everit-org/jira-worklog-query-plugin#41]
It looks like while quering intervals, duration is returned as "timespent" field
For instsance /rest/jira-worklog-query/1/find/worklogsByIssues?startDate=2016-11-07&endDate=2016-11-15&maxResults=1000&fields=issuekey,timespent
returns 
{
id: "19080",
self: "https://..../rest/api/2/issue/19080",
key: "KEY-5",
fields: {
timespent: 120
},
timespent: 60
},

Im "fields" parameter is ommited, duration also returned as timespent
Though documentatoin says it should be "duration" and not "timespent"
https://confluence.everit.biz/display/RWQD/Querying+worklogs+that+belong+to+an+interval

**Comment by bordatesz** [comment]
Hello @a-aristar ,
Thank you for your feedback. I updated the documentation, the timespent field is the correct one.

**Comment by bordatesz** [comment]
@a-aristar 
For clarification:
- The timespent in the "fields" object (in your case the value is 120) is the summary of the time spent (aka Logged Time) on the Issue. It aggregates all the time to all users. However, it excludes the sub-task logged times.
- The timespent in the outer issue object (in your case the value is 60) is the aggregated logged time for the queried user/group and in that period on the Issue.

**Comment by a-aristar** [comment]
Thanks. Just wanted to be sure about documented behaviour :)
