### ISSUE TITLE
http://{HOST}/rest/jira-worklog-query/1 Oops, you've found a dead link

### ISSUE THREAD

**Issue by asobolev01** [everit-org/jira-worklog-query-plugin#44]
Hi!

I've installed plugin from marketplace at JIRA v6.3.14#6345. 
After installing i try to reach API, but get Oops, you've found a dead link.

**Comment by bordatesz** [comment]
Hi @asobolev01 
If you are using the plugin version 1.x, the REST-API-VERSION in the URL will be the same as the plugin version until version 1.2.1 (including).

More about this in the documentation here: https://confluence.everit.biz/display/RWQD/REST+API+verison

**Comment by asobolev01** [comment]
Great! Ssory for that stupid question. $-)

**Comment by bordatesz** [comment]
glad I could help :)
