### ISSUE TITLE
Worklogs starting at 00:00 for start date not returned in results

### ISSUE THREAD

**Issue by Marczeeee** [everit-org/jira-worklog-query-plugin#45]
Hi!

I use the plugin with version 1.3.3 on a Jira 6.4.12 instance and experienced a problem: a user always records his worklogs with a start time of 00:00. When I query his worklogs with the plugin it doesn't return these worklogs starting at 00:00 for the day specified as _startDate_. If I query worklogs for 1 day (start and end date is the same) it returns an empty result even if the user had many worklogs (but all starting an midnight).
The plugin documentation says:

> "The query is run from the beginning of the given day (00:00:00)"

, but then it should return these worklogs.

**Comment by bordatesz** [comment]
Hello @Marczeeee ,
Thank you for your feedback. We'll look into it.

**Comment by bordatesz** [comment]
@Marczeeee 
If you don't mind, I have a few question:
- What JIRA version do you use?
- What type of Database do you use with JIRA?

**Comment by Marczeeee** [comment]
Sure, no problem.
- Jira version: v6.4.12#64027-sha1:e3691cc
- Database: MySQL 5.7.18

**Comment by bordatesz** [comment]
Hello @Marczeeee ,
We just released the new versions (1.3.4 and 2.1.3) with the fix. Please upgrade the add-on, try it out, and let me know if it solved your problem.

**Comment by Marczeeee** [comment]
Hello @bordatesz ,
The problem seems to be gone! Thanks for your help!
