### ISSUE TITLE
JIRA 7.4

### ISSUE THREAD

**Issue by viceice** [everit-org/jira-worklog-query-plugin#48]
Hi,

Please update the plugin for JIRA 7.4.

Regards
Michael

**Comment by daniel-toth-everit** [comment]
Hi Michael,

We have updated the marketplace version compatibility for JIRA 7.4.
If you experience any problem don't hesitate to contact us.

Best Regards,
Tóth Dániel

**Comment by viceice** [comment]
Thank, now i can upgrade to jira 7.4. I will give feedback, when i'm done.

**Comment by viceice** [comment]
Works 👍
