### ISSUE TITLE
JIRA 8.0

### ISSUE THREAD

**Issue by viceice** [everit-org/jira-worklog-query-plugin#53]
Hi,

Please update the plugin for JIRA 8.0.

Regards
Michael

**Comment by nanomader** [comment]
It doesn't work as whole or partially?

**Comment by viceice** [comment]
I don't know, I've only noticed, that jira says not compatible (upgrade checker).

**Comment by bordatesz** [comment]
Hello guys,
We are working on the compatible version and plan to release it in the next week.

**Comment by bordatesz** [comment]
Hello there,
The new Jira 8 compatible version is out and available on the Atlassian Marketplace to download.
