### ISSUE TITLE
SQL Exception from too many issueids

### ISSUE THREAD

**Issue by nahguam** [everit-org/jira-worklog-query-plugin#7]
The generated SQL query has to many predicates when a project has roughly >2000 issues.

This line must be finding too many issues that SQL can handle.
List<GenericValue> issueGvList = CoreFactory.getGenericDelegator().findByOr("Issue", issuesProjectExpr);

SQL Exception while executing the following:SELECT ID, issueid, AUTHOR, grouplevel, rolelevel, worklogbody, CREATED, UPDATEAUTHOR, UPDATED, STARTDATE, timeworked FROM hcomjira.worklog WHERE (STARTDATE >= ? ) AND (STARTDATE < ? ) AND (((AUTHOR = ? )) AND ((issueid = ? ) OR (issueid = ? ) OR (issueid = ? ) OR (issueid = ? ) OR (issueid = ? ) OR (issueid = ? ) OR (issueid = ? ) OR (issueid = ? ) OR (issueid = ? ) OR (issueid = ? ) OR (issueid = ? ) OR (issueid = ? ) OR (issueid = ? ) OR ....
((prepared or callable statement has more than 2000 parameter markers.)

**Comment by balazs-zsoldos** [comment]
Solved in 1.2.0
